[functions.send-confirmation-email]
verify_jwt = false

[functions.send-transfer-email]
verify_jwt = false

[functions.send-pickup-confirmation]
verify_jwt = false

[functions.squad-webhook]
verify_jwt = false
